serverAddr = "{{ .Envs.HOST_IP }}"
serverPort = *

auth.method = "token"
auth.token = "{{ .Envs.FRP_TOKEN }}"

transport.poolCount = 5
transport.protocol = "kcp"

[[proxies]]
name = "*.ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = *
