serverAddr = "{{ .Envs.HOST_IP }}"
serverPort = *

auth.method = "token"
auth.token = "{{ .Envs.FRP_TOKEN }}"

[[proxies]]
name = "*.ssh"
type = "tcpmux"
multiplexer = "httpconnect"
customDomains = ["machine-a"]
localIP = "*"
localPort = 22
