serverAddr = ""
serverPort = *

auth.method = "token"
auth.token = ""

[[proxies]]
name = "*.ssh"
type = "tcpmux"
multiplexer = "httpconnect"
customDomains = ["machine-a"]
localIP = "*"
localPort = 22
